const provinces = [
  "Thành phố Hà Nội",
  "Thành phố Hồ Chí Minh (TP.HCM)",
  "Thành phố Hải Phòng",
  "Thành phố Cần Thơ",
  "Thành phố Đà Nẵng",
  "Tỉnh Hà Giang",
  "Tỉnh Cao Bằng",
  "Tỉnh Lai Châu",
  "Tỉnh Lào Cai",
  "Tỉnh Tuyên Quang",
  "Tỉnh Lạng Sơn",
  "Tỉnh Bắc Kạn",
  "Tỉnh Thái Nguyên",
  "Tỉnh Yên Bái",
  "Tỉnh Sơn La",
  "Tỉnh Phú Thọ",
  "Tỉnh Vĩnh Phúc",
  "Tỉnh Bắc Giang",
  "Tỉnh Bắc Ninh",
  "Tỉnh Hải Dương",
  "Tỉnh Hưng Yên",
  "Tỉnh Hòa Bình",
  "Tỉnh Hà Nam",
  "Tỉnh Nam Định",
  "Tỉnh Ninh Bình",
  "Tỉnh Thanh Hóa",
  "Tỉnh Nghệ An",
  "Tỉnh Hà Tĩnh",
  "Tỉnh Quảng Bình",
  "Tỉnh Quảng Trị",
  "Tỉnh Thừa Thiên-Huế",
  "Tỉnh Quảng Nam",
  "Tỉnh Quảng Ngãi",
  "Tỉnh Bình Định",
  "Tỉnh Phú Yên",
  "Tỉnh Khánh Hòa",
  "Tỉnh Ninh Thuận",
  "Tỉnh Bình Thuận",
  "Tỉnh Kon Tum",
  "Tỉnh Gia Lai",
  "Tỉnh Đắk Lắk",
  "Tỉnh Đắk Nông",
  "Tỉnh Lâm Đồng",
  "Tỉnh Bình Phước",
  "Tỉnh Tây Ninh",
  "Tỉnh Bình Dương",
  "Tỉnh Đồng Nai",
  "Tỉnh Bà Rịa-Vũng Tàu",
  "Tỉnh Long An",
  "Tỉnh Tiền Giang",
  "Tỉnh Bến Tre",
  "Tỉnh Trà Vinh",
  "Tỉnh Vĩnh Long",
  "Tỉnh Đồng Tháp",
  "Tỉnh An Giang",
  "Tỉnh Kiên Giang",
  "Tỉnh Cần Thơ",
  "Tỉnh Hậu Giang",
  "Tỉnh Sóc Trăng",
  "Tỉnh Bạc Liêu",
  "Tỉnh Cà Mau",
];

const Sequelize = require("sequelize");
const sequelize = require("../utilities/database");

const User = sequelize.define("user", {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: true,
    allowNull: false,
    primaryKey: true,
  },
  firstName: Sequelize.DataTypes.STRING,
  lastName: Sequelize.DataTypes.STRING,
  age: {
    type: Sequelize.DataTypes.INTEGER,
    validate: {
      isInt: true,
      max: 200,
      min: 1,
    },
  },
  address: {
    type: Sequelize.DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [5, 150],
    },
  },
  email: {
    type: Sequelize.DataTypes.STRING,
    allowNull: false,
    validate: {
      isEmail: true,
      notEmpty: true,
      len: [5, 100],
    },
  },
});

module.exports = User;
